mbtiles:
  paths:
    - /data/london.mbtiles

postgres:
  connection_string: "postgresql://postgres:postgres@postgres:5432/realestate"
  default_srid: 4326
  auto_publish: false

  tables:
    rightmove_properties:
      layer_id: homes_layer
      schema: public
      table: rightmove_properties
      geometry_column: geom
      srid: 4326
      id_column: id
      minzoom: 13
      maxzoom: 18
      properties:
        summary: text
        bedrooms: int8
        bathrooms: int8
        displayAddress: text
        price_amount: int64
        property_sub_type: text
        displaySize_sqft: text

    boroughs:
      layer_id: boroughs_layer
      schema: public
      table: bc
      geometry_column: center_geom
      srid: 4326
      minzoom: 8
      maxzoom: 13
      properties:
        borough: text
        home_count: int64